const correctPassword = "LoydPogiReviewer"; // Set your correct password here

// Select elements
const passwordContainer = document.getElementById("passwordContainer");
const quizContainer = document.getElementById("quizContainer");
const passwordInput = document.getElementById("passwordInput");
const passwordError = document.getElementById("passwordError");
const submitPasswordButton = document.getElementById("submitPassword");

const questions = [
		{ question: "What era of gutenberg , witch is the word of mouth is the way of transition of information ", answer: "Pre-Gutenberg" },
		{ question: "What is the natural extinction rate", answer: "1 to 5 per year" },
		{ question: "BASTA", answer: "Social media" },
		{ question: "Threats to biodiversity using HIPPO", answer: "HUMAN CAUSE, INVASIVE SPECIES, POLLUTION, Population of human, OVERHARVISTING" },
		{ question: "Post gutenberg is also know as social information", answer: "True" },
		{ question: "It was during the post gutenberg, that the printing press was an avenue for freedom of expression", answer: "False (Gutenberg)" },
		{ question: "Johannes gutenberg establish the 1st form of spreading information", answer: "True" },
		{ question: "The *** biodiversity is a measure of the variety of same gene within individual speices", answer: "True" },
		{ question: "Biological diversity is biological differences ", answer: "True" },
		{ question: "The bottleneck in biodiversity occured in thousands per decade", answer: "False(5th Mass extinction)" },
		{ question: "Climate change made by human activities may not cause rapid loss and destruction of natural resources", answer: "False(Micus)" },
		{ question: "What historical period of IT revolution that involves telegraph telephone and radio", answer: "1st" },
		{ question: "Who established the first form of spreading information ", answer: "Johannes Gutenberg " },
		{ question: "When was the radio broadcasting introduce ", answer: "1920" },
		{ question: "What do you call of elemenation of speices of the natural world ", answer: "Extinction" },
		{ question: "What is an example of biodiversity hotspot that face devastation due to ilegal logging and pollution", answer: "Forest" },
		{ question: "What are the building blocks of earth that supports ecosystem", answer: "Speices" },
		{ question: "A period in human history characterized in a shift from traditional industry to economy base on information technology", answer: "Information Age" },
		{ question: "What motivates the need for communication", answer: "The need of belongingness" },
		{ question: "What are the 3 kinds of biodiversity", answer: "Speices Biodiversity , Genetic Biodiversity , Ecological Biodiversity " },
		{ question: "Information age accelerated global communications on 1980", answer: "False(1970)" },
		{ question: "During the early times communication must done through messenger pager (not sure sa pager) ", answer: "True" },
		{ question: "The first modern information revolution is also called 'Knowledge Revolution' ", answer: "False(3rd)" },
		{ question: "One Criteria *** Biodiversity Hotspot is to have atleast 2500 speices vascular plants", answer: "False(1,500)" },
		{ question: "Biodiversity spots are areas that support natural ecosystem and reservoir of biodiversity ", answer: "True" },
		{ question: "Crocodiles are important in the river ecosystem ", answer: "True" },
		{ question: "6th mass extinction is a 1-5 per year extinction rate", answer: "False(5th)" },
		{ question: "It involves insertion of 1 or more individual genes from 1 organism *** in to the DNA of another which cannot be done in conventional selective ***", answer: "Recombinant DNA technology " },
		{ question: "What do you call an organism whose genome was engineered in laboratory to obtain the desired threat", answer: "GMO" },
		{ question: "A compacted folded complex DNA and protein containing many genes they are found in the nucleus of a cell", answer: "Chromosomes" },
		{ question: "What do you call a nano in volume", answer: "Nano Liter" },
		{ question: "It refers to length of around 0.1nm to 100nm", answer: "Nano Scale" },
		{ question: "They are subunits found in the molecule in the DNA, it is very long and coiled in structure", answer: "Gene" },
		{ question: "What do you call an animal that lives by killing and eating other animal", answer: "Predator" },
		{ question: "Give the 3 major environmental application of nano technology ", answer: "Water treatment and purification, Environmental Remediation, Green Nano Composite" },
		{ question: "Give only 3 rules of GMO in food and agricultural production", answer: "Virus resistance, Pest resistance, Herbicide" },
		{ question: "Reproductive cloning is similar to recombinant dna technology", answer: "False" },
		{ question: "Other animals generated by reproductive cloning are pigs, horses and dogs", answer: "True" },
		{ question: "It was on 1984 that the nano technology has been defind by Nario taniguchi", answer: "False(1974)" },
		{ question: "Nano time is measure in nano second", answer: "True" },
		{ question: "DNA is a molecule *** nucleus of the cell that contains information for an organism development", answer: "True" },
		{ question: "It was on 2016 that republic act was passed to encourage to engage organic agriculture over GMO agriculture", answer: "False (2010)" },
		{ question: "An example of cosmetic preservation in GMO is the artic apple in which natural discoloration is suppress", answer: "True" },
		{ question: "It is an animal hunted or killed by another animal", answer: "Prey" },
		{ question: "What is the other term of GMO", answer: "Genetic Engineering (not sure) " },
		{ question: "A complete set of genetic information found in each cell of an organism ", answer: "Genome" },
		{ question: "What do you call the study and manipulation of matter at a scale of 1-100nm", answer: "Nano Technology" },
		{ question: "What contains a nano particles of other metals during the middle ages in _ where in still use in Churches now", answer: "Stained Glass Window" },
		{ question: "Where can you find the DNA in the nucleus of the cell", answer: "Chromosome " },
		{ question: "What is the goal of biotechnology ", answer: "to feed the worlds hunger" },
		{ question: "What are the nano technology issue in the PH", answer: "Health issue, Environmental Issue, Agriculture" },
		{ question: "What are the 2 scientific methods of GMO production", answer: "Recombinant DNA Technology, Reproductive Cloning" },
		{ question: "Give 1 rule of GMO in food and agricultural production", answer: "Fortification " },
		{ question: "Dolly the ship was born on 1896", answer: "False(199_)" },
		{ question: "It was during the 1st century AD where Licurgis Cup was created in rome", answer: "False(4th Century)" },
		{ question: "Molecular Beam Epitaxy is 1 of the nano technology equipment in the PH", answer: "True" },
		{ question: "Nano scale is measured in length of an inch", answer: "False(meter)" },
		{ question: "Desalination is the removal of salt and convertion of salt water to fresh water ", answer: "True" },
		{ question: "It was on 2018 that the supreme court order to put an end for ***", answer: "False(2016)" },
		{ question: "BPCorn is an example of a pest resistant plant since the BP is toxic to the worm", answer: "True" }
];

let currentQuestionIndex = 0;

// Event listener for password submission
submitPasswordButton.addEventListener("click", () => {
    const enteredPassword = passwordInput.value;
    if (enteredPassword === correctPassword) {
        // If password is correct, hide the password section and show the quiz
        passwordContainer.classList.add("hidden");
        quizContainer.classList.remove("hidden");
    } else {
        // If password is incorrect, show error message
        passwordError.classList.remove("hidden");
    }
});

// Quiz functionality
const questionElement = document.getElementById("question");
const answerElement = document.getElementById("answer");
const showAnswerButton = document.getElementById("showAnswer");
const nextQuestionButton = document.getElementById("nextQuestion");
const backQuetionButton = document.getElementById("backQuestion");

showAnswerButton.addEventListener("click", () => {
    answerElement.textContent = questions[currentQuestionIndex].answer;
    answerElement.classList.remove("hidden");
});

nextQuestionButton.addEventListener("click", () => {
    currentQuestionIndex = (currentQuestionIndex + 1) % questions.length;
    questionElement.textContent = questions[currentQuestionIndex].question;
    answerElement.textContent = "";
    answerElement.classList.add("hidden");
});

backQuetionButton.addEventListener("click", () => {
	currentQuestionIndex = (currentQuestionIndex - 1 + questions.length) % questions.length;
	questionElement.textContent = questions[currentQuestionIndex].question;
	answerElement.textContent = "";
	answerElement.classList.add("hidden");
})